### ISSUE TITLE
Add to the specification a JSON structure for the Bundle vs. requiring ZIP

### ISSUE THREAD

**Issue by swcurran** [the-human-colossus-foundation/oca-spec#10]
In our use of OCA, we don't want to use ZIP format, but would prefer to use JSON bundles. Please add to the specification what this looks like.  I think this is a more natural and useful way to represent the Bundle. If a specific instance wants to ZIP up the bundle, they can do that on the entire structure.

For example, when I use the GET /schemas endpoint for OCA Repository, I get the JSON representation of interest:

```
{
    "capture_base": {
      "type": "spec/capture_base/1.0",
      "classification": "GICS:45102010",
      "attributes": {
        "dateOfBirth": "Date",
        "dateOfExpiry": "Date",
.
.
.
        "sex": "Text",
        "signatureImage": "Binary"
      },
      "flagged_attributes": [
        "documentNumber",
.
.
.
        "photoImage",
        "optionalData"
      ]
    },
    "overlays": [
      {
        "capture_base": "EfeQBz5tyC0gett-ETgkg4pkxBwwuQoeYsT-9Nt0cNsc",
        "type": "spec/overlays/meta/1.0",
        "language": "fr",
        "name": "VIZ pour passeport numérique",
        "description": "Un formulaire à utiliser pour capturer les données de la zone d'inspection visuelle pour un passeport numérique"
      },
      {
        "capture_base": "EfeQBz5tyC0gett-ETgkg4pkxBwwuQoeYsT-9Nt0cNsc",
        "type": "spec/overlays/format/1.0",
        "attr_formats": {
          "dateOfBirth": "YYnMMnDD",
.
.
.

```

**Comment by swcurran** [comment]
I notice that the default output of the oca-rust parser tool is the JSON format.

**Comment by blelump** [comment]
Stephen,

It is indeed, yet it'll change in the foreseeable future. Likely to be something along these lines https://hackmd.io/xKOhBSBBSvC_-68pwRn-wQ

**Comment by pknowl** [comment]
There has been significant progress regarding this requirement.

@blelump, can you provide a quick update?

**Comment by pknowl** [comment]
@blelump will present the technical team's initial thoughts on a **Presentation Base** in the **DSWG call** on **Feb 8th** @ **5 pm CET** to explain their thinking to the group for an open discussion. If we can get a few presentation guys on the call that would be helpful to ensure that we get a broad consensus on the suggested approach before committing. Anyone interested in joining can email me directly at paul.knowles@humancolossus.org and I can then add you to the distribution list.

**Comment by pknowl** [comment]
Currently in the implementation stage.
